### ISSUE TITLE
Import error if scikit-learn version >20.x

### ISSUE THREAD

**Issue by alexblaessle** [KrishnaswamyLab/graphtools#34]
Hi there! 

Great package, especially in combination with PHATE. I tried installing the package yesterday (python3.7), and ran into the following import error:

````
 import phate
  File "/Users/xxx/Library/Python/3.7/lib/python/site-packages/phate/__init__.py", line 3, in <module>
    from .phate import PHATE
  File "/Users/xxx/Library/Python/3.7/lib/python/site-packages/phate/phate.py", line 10, in <module>
    import graphtools
  File "/usr/local/lib/python3.7/site-packages/graphtools/__init__.py", line 1, in <module>
    from .api import Graph, from_igraph
  File "/usr/local/lib/python3.7/site-packages/graphtools/api.py", line 6, in <module>
    from . import base
  File "/usr/local/lib/python3.7/site-packages/graphtools/base.py", line 6, in <module>
    from sklearn.utils.fixes import signature
ImportError: cannot import name 'signature' from 'sklearn.utils.fixes' (/Users/xxx/Library/Python/3.7/lib/python/site-packages/sklearn/utils/fixes.py)
````
Out of various reasons, I am using the newest development version of scikit-learn (0.21.dev0). It seems that ``signature`` was removed from ``fixes.py``.  [This](https://stackoverflow.com/questions/34457398/importerror-cannot-import-name-signature) post on SO pointed me to ``funcsigs`` and I fixed the issue by editing ``graphtools/base.py`` by changing

````
from sklearn.utils.fixes import signature
````

to

````
try: 
    from sklearn.utils.fixes import signature
except ImportError:
    from funcsigs import signature
````

It seems that issue might come up in the future, so changing the import might be useful. What do you think?

**Comment by scottgigante** [comment]
Hi @alexblaessle , thanks very much for sharing this issue in advance of the next `sklearn` release! I've looked further into it and it seems like both the `funcsigs` and the `sklearn` import of `signature` were remnants of Python 2 compatibility. Since `graphtools` dropped support for Python 2 this month, I will replace this import with

```
from inspect import signature
```

as in https://github.com/scikit-learn/scikit-learn/blob/be5d3eab97c68f6d2a9d41725266375648acddc7/sklearn/base.py#L9.

Thanks again!

**Comment by alexblaessle** [comment]
Hi @scottgigante , no worries. That was an easy one to fix ;-) . Just out of interest, is the bugfix already in pypi?

**Comment by scottgigante** [comment]
Not yet - you can install it right now with `pip install git+https://github.com/KrishnaswamyLab/graphtools@dev`. This issue will close automatically when the fix makes its way to `master`, at which time it will also be sent to PyPi. I'll endeavour to have that done before `sklearn` 0.21 is released.
