### ISSUE TITLE
spectral clustering using SVD on P is wrong

### ISSUE THREAD

**Issue by stanleyjs** [KrishnaswamyLab/graphtools#6]
P is not symmetric therefore SVD(P) != eig(P)

**Comment by scottgigante** [comment]
Is this an explicit assumption made in graphtools, that SVD(P) == eig(p)? I'm not sure this is inherently a problem.

**Comment by stanleyjs** [comment]
I was under the impression that landmark selection uses clustering on the SVD of P.   this should be on the eigenvectors instead @scottgigante
